PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS `Role`;
DROP TABLE IF EXISTS `UserRole`;
DROP TABLE IF EXISTS `Status`;
DROP TABLE IF EXISTS `Topic`;
DROP TABLE IF EXISTS `UserTopic`;
DROP TABLE IF EXISTS `Course`;
DROP TABLE IF EXISTS `UserCourse`;
DROP TABLE IF EXISTS `UserCourseUserTopic`;

PRAGMA foreign_keys = ON;
